[package]
name = "c-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
lazy_static = "1.5.0"
pcre2 = "0.2.9"
regex = "1.11.1"
tracing = "0.1.41"
tracing-forest = { version = "0.1.6", features = ["ansi"] }
